### ISSUE TITLE
HL function sensitive for differences in measurement effort

### ISSUE THREAD

**Issue by MarinkavP** [troyhill/VulnToolkit#3]
So I used your function with Dutch water level data (which you can download from: https://waterinfo.rws.nl/#!/nav/index/). For this data in 1987-07-01 there has been an increase in measurement effort, where before once every hour the water level was measured, after that date every 10 minutes. 

When I use the dataset with both these measurement efforts, the calculation of the high tides is not correct. For the data which is measured every 10 minutes, it gives negative high tides. An example: 

```
high <- HL(data$waterhoogte, data$datum_time, period = 12, phantom = TRUE, tides = "H", semidiurnal = T)
> tail(high)
       level                time tide tide2
210291    45 2020-12-31 13:00:00    H  <NA>
210292     1 2020-12-31 14:00:00    H  <NA>
210293   -48 2020-12-31 15:00:00    H  <NA>
210294   -99 2020-12-31 16:00:00    H  <NA>
210295   -39 2020-12-31 18:30:00    H  <NA>
210296    77 2020-12-31 21:00:00    H  <NA>
```

So now I split the dataset and run the function separately for the different measurement efforts and then the function works perfectly, so it is not necessary a big problem. But it is good to know this issue exists.  
If you would like to have the dataset let me know, I can send it to you (you can also download it from the website, but it is in Dutch...).

**Comment by troyhill** [comment]
Thanks for noting this behavior. `HL` does assume that the time interval between observations does not change. Since the code uses the first data points to calculate the time interval, a dataset that transitions from fine to coarse time intervals should be okay, but a dataset that shifts from coarse to fine time intervals will have issues. I'll make clearer note of this in the next update. 

The solution you describe works well. Another would be to expand the dataset to be entirely at the finest time interval, filling in with NAs. 

e.g., 
```
library(VulnToolkit)
### pull data at hourly intervals
dat.hr   <- noaa(begindate = "20200101", enddate = "20200630", station = "8467150",
             interval = "hourly")

### pull data at 6-minute intervals
dat.6min <- noaa(begindate = "20200701", enddate = "20201231", station = "8467150",
             interval = "6 minute")

dat.combined <- rbind(dat.hr, dat.6min)

### if time interval is inconsistent the high/low tides can be unreliable
HL.plot(level = dat.combined[, 2], time = dat.combined[, 1]) 

### a solution: expand coarse dataset to match the finer time intervals
timeSeq <- data.frame(time_GMT = seq.POSIXt(from = min(dat.hr$time_GMT), 
                      to = max(dat.hr$time_GMT), 
                      by = "6 min"))
dat.hr2       <- plyr::join_all(list(timeSeq, dat.hr))

### create a combined, consistently-spaced dataset
dat.combined2 <- rbind(dat.hr2, dat.6min)

HL.plot(level = dat.combined2[, 2], time = dat.combined2[, 1])  # looks better
```

For now, I think I'll note the requirement of constant spacing in the documentation and leave it to the user to ensure their data meet that requirement, rather than modifying the code to try to internally accommodate irregularly-spaced datasets.
